module.exports = {
  JWT_EXPIRATION_DATE: 30000000,
  JWT_SECRET: `bKQMZV4jMsg4:<ame?#R)x!+q.h[SUV^E(LWrfgUrHmptV2d]-}v&665LWEQ~*>{[Q`,
  ZOOM_OAUTH: `dVZqN3FiN1ZSVXFrRWVxSFlEYkJrdzpBNHFFTDhFUzJNbGVzM1IwWWtScDNkcWdKRURhR0ZCQw==`,
};
